[package]
name = "kummer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
primal = "0.3.3"
rayon = "1.11.0"

[profile.release]
debug = 1
